// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ayiwahvyewefmxfnrcxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5aXdhaHZ5ZXdlZm14Zm5yY3hjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5MTczNDIsImV4cCI6MjA2MjQ5MzM0Mn0.JD0japjW7NhSai63kMhmjNciSqf6MvRjGjnuTDjn_KM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);