// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://paqixpqryhfczlnlckrt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhcWl4cHFyeWhmY3psbmxja3J0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1ODQxNDUsImV4cCI6MjA3MTE2MDE0NX0.f68rnIiSKlZdOw8w6qwsK83Iqw_7iAMEmEUtnfPdrLc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);